FROM python:3.9-slim

WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code and templates
COPY app.py .
COPY templates templates/

# Add user and setup permissions
RUN useradd -m myuser
USER root

CMD ["python", "app.py"] 